### ISSUE TITLE
Can't select an index

### ISSUE THREAD

**Issue by serkef** [diskoverdata/diskover-community#101]
In the index selection screen, I get a message `4 indices found` but I don't see any of them, so I can't pick them. 

![image](https://user-images.githubusercontent.com/3225779/188511741-9490a9de-c023-4fa6-90c7-d61130903242.png)

**Comment by serkef** [comment]
The page in general feels a bit buggy. The purple windows do not disappear when I click X on their top right corner. Also when I click on the gear icon on the top right corner nothing happens.

**Comment by shirosaidev** [comment]
@serkef please check that you don't have any browser settings/plugins that are blocking cookies/Javascript. Also check browser console for any warnings/errors.

**Comment by serkef** [comment]
There is no error in the console.
![image](https://user-images.githubusercontent.com/3225779/189099054-651ce6dc-f752-4e84-ab56-cac948c0af9a.png)

I also tried this in a second browser (chrome 104.0.5112.101 with all add-ons disabled) and I get the same result.

**Comment by serkef** [comment]
Tried cleaning up my cookies and browsing data as well as following the other points here
https://github.com/diskoverdata/diskover-community/wiki/Diskover-v2-Usage#troubleshoot-diskover-web 

`/var/log/nginx/error.log` doesn't have anything

**Comment by serkef** [comment]
@shirosaidev any ideas about this?

**Comment by shirosaidev** [comment]
Check under Chrome inspect in the network tab, are all status 200?

**Comment by shirosaidev** [comment]
@serkef ?

**Comment by serkef** [comment]
I will check it again and post here - I'm away of my server atm. Thanks for your answer

**Comment by serkef** [comment]
@shirosaidev So I don't understand what's happening... now I'm getting a black page. and there's no error in the network tab
![image](https://user-images.githubusercontent.com/3225779/192161695-a803ccb9-c0cb-4fd5-aa18-1240fddd8044.png)

**Comment by serkef** [comment]
@shirosaidev any idea how to debug this? This makes diskover unusable for me. Indexes are created without issues though.

**Comment by shirosaidev** [comment]
what is causing that 302 redirect? Are you using proxy? Have you tried without proxy and direct to nginx web server?

**Comment by shirosaidev** [comment]
it also seems like none of the .js files are being loaded for selectindices.php page. Is there something blocking them?

**Comment by shirosaidev** [comment]
@serkef  ?

**Comment by serkef** [comment]
no I don't use a proxy, I'm using the docker image from linuxserver.
I have turned off all possible blockers.

**Comment by serkef** [comment]
I try this again on my localhost and it works:
![image](https://user-images.githubusercontent.com/3225779/197626510-8a830382-d27d-4dc0-9dc0-2d4fd31eb1d6.png)

The same docker-compose on my server doesn't work:
![image](https://user-images.githubusercontent.com/3225779/197626552-a1746da0-9f6c-430c-a2c8-07562f82ce5d.png)

So I can rule a problem on the browser.

Is there something else that controls accepted hosts maybe? 


here's my docker-compose:
```yaml
version: '2'
services:
  diskover:
    image: lscr.io/linuxserver/diskover
    container_name: diskover
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - ES_USER=elastic
      - ES_PASS=password
    volumes:
      - ./config/:/config
      - ./data/:/data
    ports:
      - 8080:80
    mem_limit: 4096m
    restart: unless-stopped
    depends_on:
      - elasticsearch
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=password
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata/:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    depends_on:
      - elasticsearch-helper
    restart: unless-stopped
  elasticsearch-helper:
    image: alpine
    command: sh -c "sysctl -w vm.max_map_count=262144"
    privileged: true
```
