### ISSUE TITLE
Feature Proposal - Timeline to Track Directory Size History

### ISSUE THREAD

**Issue by LucasFerguson** [diskoverdata/diskover-community#118]
Hi Diskover Community,

I just started using Diskover and have found it fantastic so far! I’ve been searching for a self-hosted tool to record my server's file systems for some time, but the one feature I haven’t been able to find is a way to track the history of a folder’s size and graph it on a timeline.

Diskover seems like a great foundation to develop this, but I have a couple of questions. I noticed there are many plugins listed on your website; however, they only seem accessible via contacting support. Is there a way to add plugins to the Community Edition of Diskover?

If I were to develop a plugin myself, is there a starter template or guide I could use?

Alternatively, would it make more sense to fork the project and implement this as a native feature?

I’d love to hear your thoughts!

Happily,
Lucas

**Comment by LucasFerguson** [comment]
After a bit more research I found these articles and posts:
- 2019 - by hackerman - https://www.linuxserver.io/blog/2019-06-28-getting-started-with-diskover-in-docker
- Feb 4, 2020 - by TorqueWrench- https://engineerworkshop.com/blog/how-to-monitor-disk-usage-and-growth-with-diskover/
- Jan 12, 2025 https://www.youtube.com/watch?v=Uj91tOSX

The ability to compare 2 indices is really cool! This doesn't seem to be working on my current setup as it only allows me to select one index, but I'll try re deploying the [linuxserver/diskover](https://github.com/linuxserver/docker-diskover) docker container. 

My setup
- ProxMox Virtual Environment 8.2.2
- LXC Container
  - OS: Ubuntu 22.04 
  - Docker version 27.5.1, build 9f9e405
  - Memory: 8gb
  - CPU Cores 3
  - Storage 14gb

Docker Compose:
```
version: '2'
services:
  diskover:
    image: lscr.io/linuxserver/diskover
    container_name: diskover
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - ES_HOST=elasticsearch
      - ES_PORT=9200
    volumes:
      - ./config:/config
      - /root/diskover:/data
    ports:
      - 8080:80
    mem_limit: 4096m
    restart: unless-stopped
    depends_on:
      - elasticsearch
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22
    privileged: true # Tried this to make the ulimits config work, but still received the following error 
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    depends_on:
      - elasticsearch-helper
    restart: unless-stopped
  elasticsearch-helper:
    image: alpine
    command: sh -c "sysctl -w vm.max_map_count=262144"
    privileged: true
```

I'm currently encountering the following error when attempting to use the ulimits config:
```
[+] Running 3/4
 ✔ Network root_default                   Created                                                                                                          0.1s 
 ✔ Container root-elasticsearch-helper-1  Started                                                                                                          0.2s 
 ⠼ Container elasticsearch                Starting                                                                                                         0.5s 
 ✔ Container diskover                     Created                                                                                                          0.0s 
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting rlimits for ready process: error setting rlimit type 8: operation not permitted: unknown
```

I simply commented out the ulimits config for now. The removal of this could be why a bunch of features of my instance don't work.

Any recommendations are appreciated!
Thanks,
Lucas
