### ISSUE TITLE
No search or analytics results, only dashboard works

### ISSUE THREAD

**Issue by maciekish** [diskoverdata/diskover-community#124]
Hi, i installed Diskover using the linuxserver composer stack (see below) and ran a crawl manually `docker exec diskover python3 /app/diskover/diskover.py -i diskover-$(date +%Y%m%d%H%M) /data`. It took ~17 min to crawl just over 4 million files and generated a ~1GB index in elasticsearch. After selecting this index in Diskover, it loads the dashboard just fine, but when i click `Analytics > File Tree` or `Analytics > Treemap`, absolutely nothing happens. I checked the js console and network tabs in Safari developer tools and there are no errors and no activity except for the periodic request to `check_session.php`. If i try a search instead for example files over 1GB i get the number of results and their size, but the actual list of results never loads. The only trace of any error i can find is in `nginx/error.log` which says:

### nginx/error.log
```
  thrown in /app/diskover-web/src/diskover/Diskover.php on line 1262" while reading upstream, client: 10.0.1.3, server: _, request: "GET /search.php?index=&submitted=true&p=1&q=size:%3E1048576000&doctype=file HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "diskover.***.***", referrer: "https://diskover.***.***/settings.php"
2025/05/13 17:07:24 [error] 268#268: *693 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: date_diff(): Argument #1 ($baseObject) must be of type DateTimeInterface, false given in /app/diskover-web/src/diskover/Diskover.php:1262
Stack trace:
#0 /app/diskover-web/src/diskover/Diskover.php(1262): date_diff()
#1 /app/diskover-web/public/results.php(492): calcFileRating()
#2 /app/diskover-web/public/search.php(246): include('...')
#3 {main}
```

### Docker compose
```
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "${ELASTICSEARCH_DATA}:/usr/share/elasticsearch/data"

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - "${REDIS_DATA}:/data"

  diskover:
    image: lscr.io/linuxserver/diskover:latest
    container_name: diskover
    depends_on:
      - elasticsearch
      - redis
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - USE_CRON=true        # or USE_CRON=true once indexing works
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    user: "0:0"
    volumes:
      - "${CONFIG_DIR}:/config"
      - "${DATA_DIR}:/data:ro"
    ports:
      - "8080:80"
```
