### ISSUE TITLE
How do you run a complete system under docker?

### ISSUE THREAD

**Issue by fake-name** [diskoverdata/diskover-community#54]
Basically:

 - https://hub.docker.com/r/linuxserver/diskover/
    There's a docker file in there, but it has invalid sections.
 - https://github.com/shirosaidev/diskover-web/blob/master/docker-compose.yml
   This starts up fine, but as far as I can tell doesn't have the scanner stuff?

I managed to get *most* of `https://hub.docker.com/r/linuxserver/diskover/` working by modifying the `diskover` volumes:

```
    volumes:
      - :/config
      - :/data
```
to 
```
    volumes:
      - ${HOME}/docker/config:/config
      - ${HOME}/docker/data:/data
```

But there's still issues on startup:

```
elasticsearch    | [2019-01-27T08:27:09,727][INFO ][o.e.n.Node               ] [] initializing ...
elasticsearch    | [2019-01-27T08:27:09,747][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
elasticsearch    | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
elasticsearch    |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    |      at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    |      at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    |      at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    |      at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | Caused by: java.lang.IllegalStateException: Failed to create node environment
elasticsearch    |      at org.elasticsearch.node.Node.<init>(Node.java:268) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    |      at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    |      at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    |      at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    |      at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    |      ... 6 more
elasticsearch    | Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
elasticsearch    |      at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
elasticsearch    |      at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
elasticsearch    |      at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
elasticsearch    |      at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:?]
elasticsearch    |      at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_161]
elasticsearch    |      at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_161]
elasticsearch    |      at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_161]
elasticsearch    |      at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:221) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    |      at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    |      at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    |      at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    |      at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    |      at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.9.jar:5.6.9]
```

It gets to *some* state, and I can access bits of the system:
 - `http://<server-ip>:9181/` seems to show workers, but I have no idea how to send them commands
 - `http://<server-ip>/` returns HTTP 500
 - `http://<server-ip>:9999/` also returns a HTTP 500, and an error shows up in the console:

```
diskover         | Exception in thread Thread-1:
diskover         | Traceback (most recent call last):
diskover         |   File "/app/diskover/diskover_socket_server.py", line 73, in socket_thread_handler
diskover         |     command_dict = json.loads(data)
diskover         |   File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
diskover         |     return _default_decoder.decode(s)
diskover         |   File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
diskover         |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
diskover         |   File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
diskover         |     raise JSONDecodeError("Expecting value", s, err.value) from None
diskover         | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
diskover         |
diskover         | During handling of the above exception, another exception occurred:
diskover         |
diskover         | Traceback (most recent call last):
diskover         |   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
diskover         |     self.run()
diskover         |   File "/usr/lib/python3.6/threading.py", line 864, in run
diskover         |     self._target(*self._args, **self._kwargs)
diskover         |   File "/app/diskover/diskover_socket_server.py", line 86, in socket_thread_handler
diskover         |     message = b'{"msg": "error", "error": ' + e + b'}\n'
diskover         | TypeError: can't concat JSONDecodeError to bytes
diskover         |
diskover         | 2019-01-27 08:35:39,403 [INFO][diskover] Got a connection from ('10.1.1.4', 39748)
diskover         | 2019-01-27 08:35:39,404 [INFO][diskover] Waiting for connection, listening on 0.0.0.0 port 9999 TCP (ctrl-c to shutdown)
diskover         | 2019-01-27 08:35:39,404 [INFO][diskover] [thread-1]: Got command from ('10.1.1.4', 39748)
diskover         | 2019-01-27 08:35:39,405 [ERROR][diskover] [thread-1]: Invalid JSON from ('10.1.1.4', 39748): (Expecting value: line 1 column 1 (char 0))


```

So... basically, for someone who hasn't done anything with elasticsearch, docker, etc, how do I make this do *anything*?

**Comment by CHBMB** [comment]
I've not used this before, but just got it up and running with this.

Using a custom network called `docker-network`

`docker network create docker-network`

```
docker run -d --name='elasticsearch' \
--net='docker-network' \
-e 'discovery.type'='single-node' \
'elasticsearch:5.6.14' 
```

```
docker run -d --name='redis' \
--net='docker-network' \
-p '6379:6379/tcp' \
'redis'
```

```
docker run -d --name='diskover' \
--net='docker-network' \
-e 'REDIS_HOST'='redis' \
-e 'REDIS_PORT'='6379' \
-e 'ES_HOST'='elasticsearch' \
-e 'ES_PORT'='9200' \
-e 'ES_USER'='elastic' \
-e 'ES_PASS'='changeme' \
-e 'INDEX_NAME'='diskover-' \
-e 'DISKOVER_OPTS'='' \
-e 'WORKER_OPTS'='' \
-e 'RUN_ON_START'='true' \
-e 'USE_CRON'='false' \
-e 'PUID'='99' \
-e 'PGID'='100' \
-p '9181:9181/tcp' \
-p '9999:9999/tcp' \
-p '80:80/tcp' \
-v '/path/to/diskover/config/files/':'/config':'rw' \
-v '/path/to/data/to/analyse/':'/data':'rw' \
'linuxserver/diskover'
```

**Comment by hank** [comment]
Thank you very much - I was really struggling with this until I found your comment above. If you could add that to the wiki I think others would really find it helpful.

**Comment by fake-name** [comment]
I wound up giving up and just using a couple of VMs.

I have a bunch of xen infrastructure already, so it worked out fine.

**Comment by Suika** [comment]
@fake-name long time no see.

### **java.nio.file.AccessDeniedException**
1. You are binding/mapping directories.
2. Docker runs under root.
3. Docker creates directories automatically if they do not exist.
4. The permissions are set to root.

If you use linuxserver compose file there are three directories that are mapped.
Diskover data and config, elastic data and redis data.

1. Diskover Config maps to 1000:1000
2. Elastic Data maps to 1000:1000
3. Redis maps to 999:999 but can also map to 100:102. magic
4. Diskover Data should only be read only by other.

**OR** you simply do `chmod 777 -R` on the three folders that are not Diskover data and you are good.
And don't forget to set `sysctl -w vm.max_map_count=262144`

**Comment by pdgaaa** [comment]
Hi,
I set up a docker diskover env with the docker-compose file from linuxserver.io. I ran into this permissions problem with ES, the elasticsearch/data directory is not map to 1000:1000, it was map to root:root. So I do the following : chgrp 1000 elasticsearch/data and chmod g+w elasticsearch/data
NB : redis map to user 100.

**Comment by bcurran3** [comment]
I'm having the same issue as @fake-name not being able to access the web interface. I realize this is probably more of a linuxserver.io issue (and I've posted in their forums and not received a solution yet), but figured I'd latch on here and see if someone might be able to help.

REF: https://discourse.linuxserver.io/t/linuxserver-diskover-help-cant-access-web-interface/1992

> I’ve never used Diskover. It looks cool. I’d like to check it out. I’m TRYING to check it out.
> 
> I used the posted docker-compose file from dockerhub my production home server. I changed port 80 to something else as it’s used. I edited all the volume paths to point to my local persistent storage. End result: HTTP ERROR 500 when trying to access port “80.”
> 
> Soooooooooooooooo, I setup a brand new Ubuntu 20.04 Server LTS VM to test if it was just me or or not as this has been driving me crazy. I installed Portainer via docker. I then installed linuxserver/diskover using the the default docker-compose file found on dockerhub with all default ports and just volume changes to local persistent storage. I figured this is as generic/virgin as it gets and it will work. Nope. Same problem(s).
> 
> RESULTS:
> IP:80 " 502 Bad Gateway" or “HTTP ERROR 500”
> IP:9181 - RQ dashboard displays
> IP:9999 - “ERR_INVALID_HTTP_RESPONSE”
> (I’m guessing 9999 is not supposed to be interactive as I see the Invalid JSON from … in the logs)
> 
> Meanwhile the elasticsearch container keeps stopping. I see the logs saying:
> [2020-08-28T00:59:42,195][INFO ][o.e.b.BootstrapChecks ] [0ZdlJdz] bound or publishing to a non-loopback address, enforcing bootstrap checks
> ERROR: [1] bootstrap checks failed
> [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
> 
> yes, I’ve seen the notes on the page " ElasticSearch also requires a sysctl setting on the host machine to run properly. Running sysctl -w vm.max_map_count=262144 will solve this issue. To make this setting persistent through reboots, set this value in /etc/sysctl.conf ." but don’t understand why this isn’t configured in the container by default. Normally no big deal I’d just go and do as told, but the container keeps stopping before I can get a bash prompt on it.
> 
> I’ve chmod +777’d all the data directories.
> I’ve added changed PUID and PGID variables to 0 for all the containers
> …and it made no difference
> I’ve search on Discourse on here.
> I’ve searched documenation.
> 
> I’m stuck!
> I want pretty pictures and graphs in my web browser. :slight_smile:
> What am I doing wrong?

First docker-compose:

```
version: '2'
services:
  diskover:
    image: linuxserver/diskover
    container_name: diskover
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Americas/LosAngeles
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - ES_USER=elastic
      - ES_PASS=changeme
      - RUN_ON_START=true
      - USE_CRON=true
    volumes:
      - /data/docker/diskover/config:/config
      - /data/docker/diskover/data:/data
    ports:
      - 80:80
      - 9181:9181
      - 9999:9999
    mem_limit: 4096m
    restart: unless-stopped
    depends_on:
      - elasticsearch
      - redis
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
    volumes:
      - /data/docker/diskover/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - /data/docker/diskover/redis/data:/data
```

2nd docker-compose:

```
version: '2'
services:
  diskover:
    image: linuxserver/diskover
    container_name: diskover
    environment:
      - PUID=0
      - PGID=0
      - TZ=Americas/LosAngeles
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - ES_USER=elastic
      - ES_PASS=changeme
      - RUN_ON_START=true
      - USE_CRON=true
    volumes:
      - /data/docker/diskover/config:/config
      - /data/docker/diskover/data:/data
    ports:
      - 80:80
      - 9181:9181
      - 9999:9999
    mem_limit: 4096m
    restart: unless-stopped
    depends_on:
      - elasticsearch
      - redis
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
    volumes:
      - /data/docker/diskover/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - PUID=0
      - PGID=0
    ulimits:
      memlock:
        soft: -1
        hard: -1
  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - /data/docker/diskover/redis/data:/data
      - PUID=0
      - PGID=0
```

I was going to say I'll try putting it on it's on network, but with only Portainer running I doubt it will help. Any suggestions?

And if you want me to create my own issue, just say so.
